// export function setupCounter(element) {
//   let counter = 0
//   const setCounter = (count) => {
//     counter = count
//     element.innerHTML = `count is ${counter}`
//   }
//   element.addEventListener('click', () => setCounter(counter + 1))
//   setCounter(0)
// }
// /* Background styles */
// body {
//   background-image: url('https://images.unsplash.com/photo-1519681393784-d120267933ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1124&q=100');
//   background-position: center;
// }

// /* Glassmorphism card effect */
// .card {
//   backdrop-filter: blur(16px) saturate(180%);
//   -webkit-backdrop-filter: blur(16px) saturate(180%);
//   background-color: rgba(17, 25, 40, 0.54);
//   border-radius: 12px;
//   border: 1px solid rgba(255, 255, 255, 0.125);
// }

// /* Generated by https://generator.ui.glass/ */

// .card {
//   width: 190px;
//   height: 254px;
//   transition: all 0.2s;
//   position: relative;
//   cursor: pointer;
// }

// .card-inner {
//   width: inherit;
//   height: inherit;
//   background: rgba(255,255,255,.05);
//   box-shadow: 0 0 10px rgba(0,0,0,0.25);
//   backdrop-filter: blur(10px);
//   border-radius: 8px;
// }

// .card:hover {
//   transform: scale(1.04) rotate(1deg);
// }

// .circle {
//   width: 100px;
//   height: 100px;
//   background: radial-gradient(#b0e633, #53ef7d);
//   border-radius: 50%;
//   position: absolute;
//   animation: move-up6 2s ease-in infinite alternate-reverse;
// }

// .circle:nth-child(1) {
//   top: -25px;
//   left: -25px;
// }

// .circle:nth-child(2) {
//   bottom: -25px;
//   right: -25px;
//   animation-name: move-down1;
// }

// @keyframes move-up6 {
//   to {
//     transform: translateY(-10px);
//   }
// }

// @keyframes move-down1 {
//   to {
//     transform: translateY(10px);
//   }
// }

// <div class="card">
//     <div class="circle"></div>
//     <div class="circle"></div>
//     <div class="card-inner">23</div>
// </div>
